services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    Plenta\ContaoTidyUpBundle\:
        resource: ../../*
        exclude: ../../{Entity,Migrations,Resources}