services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    Plenta\ContaoTidyUpBundle\:
        resource: ../../*
        exclude: ../../{Entity,Migrations,Resources}

    Plenta\ContaoTidyUpBundle\Classes\TidyUpModules:
        public: true

    Plenta\ContaoTidyUpBundle\Classes\TidyUpTemplates:
        public: true